version: "3"

services:
    # image project
    frontend_vue:
        build:
            context: ./
            dockerfile: Dockerfile
        ports: 
            - '80:80'
        restart: unless-stopped