version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks: 
            - php
    
    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8080:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - php

networks: 
    php:
        driver: bridge
